### ISSUE TITLE
Add support for spline profile, and add documentation on website

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/Stellarator-Database#2]
Just need to make some sort of util function like

```python
def get_profile_data(profile):
# profile is a DESC Profile object
     if isinstance(profile, PowerSeriesProfile):
        data_profile["profile_type"] = "power_series"
        data_profile["profile_data1"] = profile.basis.modes[:, 0]
        data_profile["profile_data2"] = profile.params
    elif isinstance(profile, SplineProfile):
        data_profile["profile_type"] = "spline"
        data_profile["profile_data1"] = profile.knots
        data_profile["profile_data2"] = profile.params
     return data_profile
```

also should add to website the info on what data1 and data2 mean for the different profile types (data1 is modes if power series but knots if spline, etc)

**Comment by YigitElma** [comment]
@dpanici I changed how we get profile info. If I am correct, the new version should support every profile type except for the `MTanhProfile`

**Comment by YigitElma** [comment]
https://github.com/PlasmaControl/Stellarator-Database/blob/main/stelladb/db_desc.py#L997

**Comment by YigitElma** [comment]
@dpanici please check this once you have time. Reopen this if you think there is a bug!
