### ISSUE TITLE
Change `D_Mercier` and any other radial profile data to be computed for a grid with only radial nodes

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/Stellarator-Database#3]
Right now, the grid that the Mercier stability is computed on has poloidal resolution, but Mercier stability is a flux surface average quantity, so the database column for mercier has a lot of repeated numbers since the quantity is constant on each flux surface.

Should only calculate radial profile quantities on a grid with only radial nodes (M=0 N=0)

**Comment by YigitElma** [comment]
It should have been resolved by this.
https://github.com/PlasmaControl/Stellarator-Database/blob/main/stelladb/db_desc.py#L911
